d_emb: 768
d_head: 32
d_hidden: 256
dropout: 0.2
feature_map: SMReg
ignore_list: null
lr: 0.0001
max_ids: 87
mode: 0
n_blocks: 8
n_features: 9
n_head: 8
rotary_emb_list:
- 2
use_linear_att: true
weight_decay: 0.0001
