d_emb: 768
d_head: 16
d_hidden: 128
dropout: 0.3
feature_map: SMReg
ignore_list: null
lr: 5.0e-05
max_ids: 87
mode: 0
n_blocks: 6
n_features: 6
n_head: 8
rotary_emb_list:
- 2
use_linear_att: true
weight_decay: 0.0001
